<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
  </ItemGroup>

 <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\IdentityCore.AutoMapper\IdentityCore.AutoMapper.csproj" />
    <ProjectReference Include="..\IdentityCore.EFs\IdentityCore.EFs.csproj" />
    <ProjectReference Include="..\IdentityCore.Repository\IdentityCore.Repository.csproj" />
  </ItemGroup>

</Project>
